### ISSUE TITLE
What should I do when listener connection lifetime ends?

### ISSUE THREAD

**Issue by a-barbieri** [sanity-io/client#12]
Currently Sanity has a 30 minutes limit for the listener connection lifetime. 

Does it mean that I should rerun `client.listen(myquery)` every 30 minutes to make sure the user doesn't see a stale version of the dataset?

Should I inform the user?

is the library doing something to avoid presenting stale data?

See [Sanity documentation](https://www.sanity.io/docs/technical-limits#4877107a788a).

**Comment by stipsan** [comment]
> Does it mean that I should rerun client.listen(myquery) every 30 minutes to make sure the user doesn't see a stale version of the dataset?
No, we handle the 30 minute timeout for you. You should only rerun `client.listen` as part of your error handling, as the observer will emit an error and stop the internal listener.

> Should I inform the user?
In most cases you don't, however it's good practice to show UI on offline/online events so that if the user is offline they know why the data might be stale.

> is the library doing something to avoid presenting stale data?
Yes: https://github.com/sanity-io/client/blob/da0d23c16f18ea437b1924a09e1eaf20644c2882/src/data/listen.ts#L105-L115
